In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# 특징(feature)이 하나일때의 노드

python class에서<br>
\__init__ => 객체 생성시 변수 초기화를 위해 실행됨<br>
\__call__ => 인스턴스 실행 시 실행됨

In [2]:
class OneFeatureNode:
    def __init__(self):
        self.w = tf.Variable([[0.1]])
        self.b = tf.Variable([[0.5]])
        
    def __call__(self, x):
        return self.get_output(x)
    
    def get_output(self, x):
        output = tf.matmul(x, self.w)
        print('행렬곱 결과:', output.numpy())
        output = tf.add(output, self.b)
        print('행렬합 결과:', output.numpy())
        output = tf.math.sigmoid(output)
        print('시그모이드 후 결과:', output.numpy())
        return output

In [3]:
x = tf.constant([[1.0]])

one_feature_node = OneFeatureNode()
one_feature_node(x)

행렬곱 결과: [[0.1]]
행렬합 결과: [[0.6]]
시그모이드 후 결과: [[0.6456563]]


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.6456563]], dtype=float32)>

# 특징(feature)이 두개일때의 노드

In [4]:
class TwoFeaturesNode:
    def __init__(self):
        self.w = tf.Variable([[0.1], [0.2]])
        self.b = tf.Variable([[0.5]])
        
    def __call__(self, x):
        return self.get_output(x)
    
    def get_output(self, x):
        output = tf.matmul(x, self.w)
        print('행렬곱 결과:', output.numpy())
        output = tf.add(output, self.b)
        print('행렬합 결과:', output.numpy())
        output = tf.math.sigmoid(output)
        print('시그모이드 후 결과:', output.numpy())
        return output

In [5]:
x = tf.constant([[1.0, 2.0]])
two_features_node = TwoFeaturesNode()
two_features_node(x)

행렬곱 결과: [[0.5]]
행렬합 결과: [[1.]]
시그모이드 후 결과: [[0.7310586]]


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.7310586]], dtype=float32)>

# Input이 n개인 특징(feature)이 2개인 노드

In [6]:
x = ([[1.0, 2.0], [2.0, 3.0], [4.0, 5.0]])
two_features_node = TwoFeaturesNode()
two_features_node(x)

행렬곱 결과: [[0.5]
 [0.8]
 [1.4]]
행렬합 결과: [[1. ]
 [1.3]
 [1.9]]
시그모이드 후 결과: [[0.7310586]
 [0.785835 ]
 [0.8698916]]


<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.7310586],
       [0.785835 ],
       [0.8698916]], dtype=float32)>