In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a1 = [0.2, 3, 2]
a2 = [-1, 5, 0.2]
a3 = [0.5, 2, -0.1]

-----------------------
# One To One
<img src="./source/one_to_one.png" width="150">

In [3]:
x_data = np.array([[a1]], dtype=np.float32)

output_dim = 2
rnn = tf.keras.layers.SimpleRNN(units=output_dim, return_sequences=True, return_state=True)
# lstm = tf.keras.layers.LSTM(units=output_dim, return_sequences=True, return_state=True)
# gru = tf.keras.layers.GRU(units=output_dim, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[0.2 3.  2. ]]], shape: (1, 1, 3)
outputs: [[[-0.38929304  0.96568   ]]], shape: (1, 1, 2)
states: [[-0.38929304  0.96568   ]], shape: (1, 2)


----------------------
# Many To Many
<img src="./source/many_to_many.png" width="550px">

In [4]:
x_data = np.array([[a1, a2, a3]], dtype=np.float32)

output_dim = 2
rnn = tf.keras.layers.SimpleRNN(units=output_dim, return_sequences=True, return_state=True)
# lstm = tf.keras.layers.LSTM(units=output_dim, return_sequences=True, return_state=True)
# gru = tf.keras.layers.GRU(units=output_dim, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[ 0.2  3.   2. ]
  [-1.   5.   0.2]
  [ 0.5  2.  -0.1]]], shape: (1, 3, 3)
outputs: [[[-0.9512081  -0.9824984 ]
  [-0.99997103 -0.9999817 ]
  [-0.97390765 -0.9964803 ]]], shape: (1, 3, 2)
states: [[-0.97390765 -0.9964803 ]], shape: (1, 2)


-----------------------------
# Many To One
<img src="./source/many_to_one.png" width="250">

In [5]:
x_data = np.array([[a1, a2, a3]], dtype=np.float32)

output_dim = 2
rnn = tf.keras.layers.SimpleRNN(units=output_dim, return_sequences=False, return_state=True)
# lstm = tf.keras.layers.LSTM(units=output_dim, return_sequences=True, return_state=True)
# gru = tf.keras.layers.GRU(units=output_dim, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[ 0.2  3.   2. ]
  [-1.   5.   0.2]
  [ 0.5  2.  -0.1]]], shape: (1, 3, 3)
outputs: [[-0.36172506  0.8333647 ]], shape: (1, 2)
states: [[-0.36172506  0.8333647 ]], shape: (1, 2)
